//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class administracion
    {
        public int id_admi { get; set; }
        public string nombre_admi { get; set; }
        public string contrasena_admi { get; set; }
        public string direccion_admi { get; set; }
        public Nullable<int> telefono_admi { get; set; }
        public Nullable<int> fk_veterinario { get; set; }
        public Nullable<int> fk_mascota { get; set; }
        public Nullable<int> fk_vacuna { get; set; }
    
        public virtual mascotas mascotas { get; set; }
        public virtual vacunas vacunas { get; set; }
        public virtual veterinarios veterinarios { get; set; }
    }
}
