//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class mascotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mascotas()
        {
            this.administracion = new HashSet<administracion>();
        }
    
        public int id { get; set; }
        public string nombre_mascota { get; set; }
        public Nullable<int> edad_mascota { get; set; }
        public string raza { get; set; }
        public Nullable<int> peso { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> fk_cliente { get; set; }
        public Nullable<int> fk_vacuna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<administracion> administracion { get; set; }
        public virtual clientes clientes { get; set; }
        public virtual vacunas vacunas { get; set; }
    }
}
