//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class veterinariaEntities : DbContext
    {
        public veterinariaEntities()
            : base("name=veterinariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administracion> administracion { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<mascotas> mascotas { get; set; }
        public virtual DbSet<vacunas> vacunas { get; set; }
        public virtual DbSet<veterinarios> veterinarios { get; set; }
    }
}
