//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class veterinarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public veterinarios()
        {
            this.administracion = new HashSet<administracion>();
        }
    
        public int cedula_vet { get; set; }
        public string nombre_vet { get; set; }
        public string nombre_usuv { get; set; }
        public Nullable<int> edad_vet { get; set; }
        public string direccion_vet { get; set; }
        public string correo_vet { get; set; }
        public Nullable<int> telefono_vet { get; set; }
        public string eps { get; set; }
        public string contrasena_vet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<administracion> administracion { get; set; }
    }
}
